### ISSUE TITLE
Anki 23.10.1 error

### ISSUE THREAD

**Issue by omega3** [lambdadog/passfail2#13]
```

Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Platform: Linux-6.6.7-1-MANJARO-x86_64-with-glibc2.38
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-19 10:35:27
Add-ons possibly involved: ⁨PassFail 2 Remove the Easy and Hard buttons⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 628, in handler
  File "aqt.reviewer", line 652, in _onTypedAnswer
  File "aqt.reviewer", line 403, in _showAnswer
  File "aqt.reviewer", line 710, in _showEaseButtons
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "/home/user/Anki2/addons21/PassFail2 Remove the Easy and Hard buttons 876946123/__init__.py", line 47, in pfAnswerButtons
    buf += but(ease, label, shortcutDialog)
  File "/home/user/Anki2/addons21/PassFail2 Remove the Easy and Hard buttons 876946123/__init__.py", line 41, in but
    due = self._buttonTime(i)
TypeError: _buttonTime() missing 1 required positional argument: 'v3_labels'

```

**Comment by lambdadog** [comment]
Thank you for reporting! Sadly it's been a while since I've been actively using Anki, so the project has gone a bit unmaintained. I'll try and take a look at fixing this soon.

**Comment by RohanModi-CA** [comment]
Unable to replicate on VirtualBox Manjaro 6.9.0-1 QT5, Anki 23.10.1

Perhaps the issue has resolved itself with Kernel updates?
